### ISSUE TITLE
Compatibility of ubuntu:latest

### ISSUE THREAD

**Issue by SeanPesce** [ar0x4/ysoserial.net-docker#1]
For anyone else who runs into compatibility issues with the latest Ubuntu image, this fix worked for me:

Change the first line of [Dockerfile](https://github.com/ar0x4/ysoserial.net-docker/blob/master/Dockerfile) to use `ubuntu:22.04`:

```
FROM ubuntu:22.04
```

**Comment by ar0x4** [comment]
Thanks Sean!
It's fixed now.
